### PR TITLE
WIP: Finish Sports Page

### PR DESCRIPTION
**Pull request by aubgolympics**
https://github.com/AUBG-Olympics/website/issues/43

The following pull request adds links to rules to the sports as well as icons. The Skills Challenge is missing rules since they are TBD (therefore, the Rules button is hidden). @Pastedko

### CODE REVIEW

**Comment by Pastedko** [comment]
Pictures are not the correct ratio.

**Comment by Pastedko** [comment]
What is this color for the mobile menu?

Everything else looks good.
@g-slavov

**Comment by aubgolympics** [comment]
Which pictures are not in the correct ratio?

I am not sure what you mean by mobile menu color. Everything should stay the same in terms of color.

@Pastedko

**Comment by Pastedko** [comment]
image
image

For me they seem a bit stretched.


My bad for the color. Opera GX dark mode. Apologies. @g-slavov

**Review by Pastedko — DISMISSED** [review]

**Pull request merged**
