### PR TITLE
feat: add responsive design to sports page and prepare for sign up

### PR DESCRIPTION
**Pull request by aubgolympics**
When testing the responsiveness of the Sports page, make sure to remove the Navigation element since right now it causes a weird behavior on the page. You can check out the built-in emulator of the browser.

So far, I have tested the responsiveness on the page only on Microsoft Edge. Please, check it out on Chrome and Safari (@marioboyanov can help with the Safari browser).

### CODE REVIEW

**Comment by Pastedko** [comment]
image
Title is not centered

**Comment by Pastedko** [comment]
image

Doesn't work on 320px width. (Is kind of irrelevant but decided to mention it anyway)

**Comment by Pastedko** [comment]
image

Elements are not centered

**Review by Pastedko — APPROVED** [review]
Good job Slavov!

**Review by marioboyanov — APPROVED** [review]

**Pull request merged**
